name: PartyGame
version: '1.0-SNAPSHOT'
main: my.cufee.partygame.PartyGame
api-version: '1.20'

commands:
  pgjoin:
    description: Присоедениться к игре.
  pgcreate:
    description: Создать игру.
  pgleave:
    description: Покинуть игру.
  pgdelete:
    description: Удалить игру.